language: ruby
rvm:
  - jruby-1.7.24
  - jruby-9.0.5.0
branches:
  only:
    - master
services:
  - redis-server
env:
  - resque="master" delayed_job="~>4.1"
  - resque="~>1.25.2" delayed_job="~>4.0"
  - resque="~>1.24.1" delayed_job="~>3.0"
  - resque="~>1.23.1" delayed_job="~>2.1"
